apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-data-claim
  labels:
    app: grafana
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeName: "grafana-data"